"""Generate the theme showcase: the same one-scene story rendered in each of
the 8 bundled brand presets, screenshotted full-page, written to docs/themes/.

Usage:  uv run python scripts/build_theme_gallery.py
Needs the [vet] extra + `playwright install chromium` + network (CDN libs).
"""

from __future__ import annotations

import html as html_mod
import sys
import tempfile
from pathlib import Path

from dstory import Brand, build, list_presets, recipe_js
from dstory.cookbook import RECIPE_DEMOS

DOCS_THEMES = Path(__file__).resolve().parent.parent / "docs" / "themes"


def render_screenshots(out_dir: Path) -> None:
    from playwright.sync_api import sync_playwright

    demo = RECIPE_DEMOS["line-reveal"]
    tmp = Path(tempfile.mkdtemp(prefix="dstory-themes-"))

    with sync_playwright() as p:
        browser = p.chromium.launch()
        page = browser.new_page(viewport={"width": 1000, "height": 800},
                                reduced_motion="reduce")
        for theme in list_presets():
            result = build(
                {"meta": {"title": "The Shape of a Quarter",
                          "subtitle": "A dstory theme preview",
                          "deck": "The same story, eight personalities.",
                          "author": "dstory", "published": "2026",
                          "theme": theme},
                 "scenes": [{"id": "scene-trend", "dataset": "trend", **demo["scene"]}],
                 "datasets": {"trend": demo["dataset"]}},
                tmp / theme,
                scenes={"scene-trend": recipe_js("line-reveal", "scene-trend")},
            )
            page.goto(result.html.as_uri(), wait_until="load")
            page.wait_for_selector('[data-mount="scene-trend"] svg', timeout=15000)
            page.wait_for_timeout(400)
            shot = out_dir / f"{theme}.png"
            page.screenshot(path=str(shot), full_page=True)
            print(f"  rendered {shot.name}")
        browser.close()


def write_index(out_dir: Path) -> None:
    esc = html_mod.escape
    cards = []
    for theme in list_presets():
        b = Brand.from_preset(theme)
        desc = b.config.get("brand", {}).get("description", "")
        accent = b.colors.get("accent", "#888")
        cards.append(f"""\
    <figure class="card">
      <a href="{esc(theme)}.png"><img src="{esc(theme)}.png" alt="The preview story rendered in the {esc(theme)} theme" loading="lazy"></a>
      <figcaption>
        <h2><span class="chip" style="background:{esc(accent)}"></span>{esc(theme)}</h2>
        <p>{esc(desc)}</p>
        <code>dstory init my-story --theme {esc(theme)}</code>
      </figcaption>
    </figure>""")

    page = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>dstory themes</title>
<style>
  body {{ margin: 0; padding: 3rem 1.5rem; background: #faf7f2; color: #1a1a1a;
         font: 16px/1.55 system-ui, sans-serif; }}
  header {{ max-width: 72rem; margin: 0 auto 3rem; }}
  h1 {{ font-size: 2.2rem; margin: 0 0 0.5rem; }}
  header p {{ color: #555; max-width: 56ch; }}
  .grid {{ max-width: 72rem; margin: 0 auto; display: grid; gap: 2rem;
          grid-template-columns: repeat(auto-fill, minmax(300px, 1fr)); }}
  .card {{ margin: 0; background: #fff; border: 1px solid #e4ded4; border-radius: 6px;
          overflow: hidden; }}
  .card img {{ width: 100%; height: 280px; object-fit: cover; object-position: top;
              display: block; }}
  figcaption {{ padding: 1rem 1.25rem 1.25rem; }}
  h2 {{ font-size: 1.05rem; margin: 0 0 0.35rem; display: flex; align-items: center; gap: 0.5rem; }}
  .chip {{ width: 14px; height: 14px; border-radius: 4px; display: inline-block;
          border: 1px solid rgba(0,0,0,0.15); }}
  figcaption p {{ margin: 0 0 0.75rem; color: #555; font-size: 0.9rem; min-height: 2.7em; }}
  code {{ display: block; font-size: 0.78rem; background: #f3efe8; padding: 0.5rem 0.6rem;
         border-radius: 4px; overflow-x: auto; }}
  footer {{ max-width: 72rem; margin: 3rem auto 0; color: #777; font-size: 0.85rem; }}
  a {{ color: inherit; }}
</style>
</head>
<body>
<header>
  <h1>dstory themes</h1>
  <p>The same one-scene story rendered in each of the 8 bundled brand presets.
     A brand is a TOML file — extend any preset with your own colors and
     typography without touching source code.</p>
</header>
<div class="grid">
{chr(10).join(cards)}
</div>
<footer>
  Generated by <code style="display:inline;padding:0.1rem 0.3rem">scripts/build_theme_gallery.py</code> ·
  <a href="../index.html">docs</a> ·
  <a href="../gallery/index.html">cookbook gallery</a> ·
  <a href="../demo/index.html">demo story</a>
</footer>
</body>
</html>
"""
    (out_dir / "index.html").write_text(page, encoding="utf-8")
    print(f"  wrote {out_dir / 'index.html'}")


def main() -> int:
    DOCS_THEMES.mkdir(parents=True, exist_ok=True)
    render_screenshots(DOCS_THEMES)
    write_index(DOCS_THEMES)
    return 0


if __name__ == "__main__":
    sys.exit(main())
